### ISSUE TITLE
Crash with missing rederscript

### ISSUE THREAD

**Issue by chad-cmb** [persona-id/inquiry-android-2#2] opened 2023-04-10 17:04 UTC
We have a few of these crashes show up over the weekend on Android 8 devices (and one Android 10). 

Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.coffeemeetsbagel-EFE3w2JcdZFDgI9CXvbc6g==/base.apk"],nativeLibraryDirectories=[/data/app/com.coffeemeetsbagel-EFE3w2JcdZFDgI9CXvbc6g==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "librenderscript-toolkit.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
       at java.lang.System.loadLibrary(System.java:1667)
       at com.google.android.renderscript.Toolkit.<clinit>(Toolkit.kt:1093)
       at com.withpersona.sdk2.camera.analyzers.BarcodePdf417Analyzer.sharpenImage(BarcodePdf417Analyzer.kt)
       at com.withpersona.sdk2.camera.analyzers.BarcodePdf417Analyzer.analyze-IoAF18A(BarcodePdf417Analyzer.kt:37)
       at com.withpersona.sdk2.camera.GovernmentIdFeed.analyze(GovernmentIdFeed.kt:52)
       at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$2(ImageAnalysis.java)
       at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0(ImageAnalysisAbstractAnalyzer.java:285)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

<img width="434" alt="Screen Shot 2023-04-10 at 12 04 28 PM" src="https://user-images.githubusercontent.com/92877129/230952670-72d3fed9-0354-4269-8dce-e037528e0528.png">

**Comment by chrispix99** [comment] 2023-04-10 17:39
FYI: this is using  com.withpersona.sdk2:inquiry:2.3.5

**Comment by jacoblange-dev** [comment] 2023-04-10 17:52
Thanks for the report, filed this issue internally. Closing this but we'll comment when a fix goes out.

**Closed as completed by jacoblange-dev** 2023-04-10 17:52 UTC

**Comment by idunnololz** [comment] 2023-04-10 18:32
An update on this.

We use Android NDK for image processing purposes. Android NDK builds generate versions of the code for different architectures.  At the time of writing, the supported architectures are here: https://developer.android.com/ndk/guides/abis#sa. The important thing to note here is that they are expected to be in folders
```
/lib/armeabi
/lib/armeabi-v7a
/lib/arm64-v8a
/lib/x86
/lib/x86_64
```

Now if we look at the crash report we can see the following 
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.coffeemeetsbagel-EFE3w2JcdZFDgI9CXvbc6g==/base.apk"],nativeLibraryDirectories=[/data/app/com.coffeemeetsbagel-EFE3w2JcdZFDgI9CXvbc6g==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "librenderscript-toolkit.so"
```
The interesting part is `[/data/app/com.coffeemeetsbagel-EFE3w2JcdZFDgI9CXvbc6g==/lib/arm64, /system/lib64, /system/product/lib64]`. This indicates that the directories that were searched were `/lib/arm64`, `/system/lib64`, `/system/product/lib64`. But Android NDK does not generate a `/lib/arm64` folder. It generates a `/lib/arm64-v8a` folder.

We are not sure of the cause of this at this time. It could be a bug within the OS itself. Going forward we will try to catch these exceptions as the image processing we do with the NDK is optional. You can expect these changes in the next SDK update.
